# Fixtures needed for puppetlabs_spec_helper
fixtures:
  repositories:
    r10k:
      repo: 'git://github.com/acidprime/r10k.git'
      ref: 'v1.0.2'
    ruby:
      repo: 'git://github.com/puppetlabs/puppetlabs-ruby.git'
      ref: '0.1.1'
    yamlfile:
      repo: 'git://github.com/reidmv/puppet-module-yamlfile.git'
    filemapper:
      repo: 'git://github.com/adrienthebo/puppet-filemapper.git'
      ref: '1.1.2'
    account:
      repo: 'git://github.com/jenkins-infra/puppet-account.git'
      ref: '03280b8'
    sudo:
      repo: 'git://github.com/saz/puppet-sudo.git'
      ref: 'v3.0.6'
    irc:
      repo: 'git://github.com/jenkins-infra/puppet-irc.git'
      ref: 'ca69ffa'
    docker:
      repo: 'git://github.com/garethr/garethr-docker.git'
      ref: '9c5be9b'
    apache-logcompressor:
      repo: 'git://github.com/jenkins-infra/puppet-apache-logcompressor.git'

  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.1.0'
    firewall:
      repo: 'puppetlabs/firewall'
      ref: '1.0.2'
    apache:
      repo: 'puppetlabs/apache'
      ref: '1.0.1'
    git:
      repo: 'puppetlabs/git'
      ref: '0.0.3'
    ntp:
      repo: 'puppetlabs/ntp'
      ref: '3.0.3'
    inifile:
      repo: 'puppetlabs/inifile'
      ref: '1.0.3'
    apt:
      repo: 'puppetlabs/apt'
      ref: '1.4.2'
    concat:
      repo: 'puppetlabs/concat'
      ref: '1.0.2'


# Setting up a couple of symlinks to make it easier to treat profiles and roles
# just as another set of "modules" in our environment
  symlinks:
    profile: "#{source_dir}/dist/profile"
    role: "#{source_dir}/dist/role"
