# Fixtures needed for puppetlabs_spec_helper
fixtures:
  repositories:
    yamlfile:
      repo: 'git://github.com/reidmv/puppet-module-yamlfile.git'
    filemapper:
      repo: 'git://github.com/adrienthebo/puppet-filemapper.git'
      ref: '1.1.2'
    account:
      repo: 'git://github.com/jenkins-infra/puppet-account.git'
      ref: '0d949ae'
    sudo:
      repo: 'git://github.com/saz/puppet-sudo.git'
      ref: 'v3.0.6'
    irc:
      repo: 'git://github.com/jenkins-infra/puppet-irc.git'
      ref: '4e5e437'
    docker:
      repo: 'git://github.com/jenkins-infra/garethr-docker.git'
      ref: '951781fbeb06fa8142e851c5746c35b302a6f427'
    apachelogcompressor:
      repo: 'git://github.com/jenkins-infra/puppet-apachelogcompressor.git'

  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.9.0'
    datadog_agent:
      repo: 'datadog/datadog_agent'
      ref: '1.6.0'
    r10k:
      repo: 'zack/r10k'
      ref: '3.1.1'
    ruby:
      repo: 'puppetlabs/ruby'
      ref: '0.4.0'
    firewall:
      repo: 'puppetlabs/firewall'
      ref: '1.1.3'
    apache:
      repo: 'puppetlabs/apache'
      ref: '1.8.1'
    git:
      repo: 'puppetlabs/git'
      ref: '0.4.0'
    ntp:
      repo: 'puppetlabs/ntp'
      ref: '4.1.2'
    inifile:
      repo: 'puppetlabs/inifile'
      ref: '1.4.3'
    apt:
      repo: 'puppetlabs/apt'
      ref: '1.6.0'
    concat:
      repo: 'puppetlabs/concat'
      ref: '1.2.5'
    staging:
      repo: 'nanliu/staging'
      ref: '0.4.0'
    groovy:
      repo: 'rtyler/groovy'
      ref: '1.0.1'
    ssh:
      repo: 'saz/ssh'
      ref: '2.3.6'
    lvm:
      repo: 'puppetlabs/lvm'
      ref: '0.3.2'
    gcc:
      repo: 'puppetlabs/gcc'
      ref: '0.3.0'
    vcsrepo:
      repo: 'puppetlabs/vcsrepo'
      ref: '1.1.0'
    puppetserver_gem:
      repo: 'puppetlabs/puppetserver_gem'
      ref: '0.2.0'
    letsencrypt:
      repo: 'danzilio/letsencrypt'
      ref: '1.0.0'
    openldap:
      repo: 'camptocamp/openldaap'
      ref: '1.14.0'


# Setting up a couple of symlinks to make it easier to treat profiles and roles
# just as another set of "modules" in our environment
  symlinks:
    profile: "#{source_dir}/dist/profile"
    role: "#{source_dir}/dist/role"
