# Fixtures needed for puppetlabs_spec_helper
fixtures:
  repositories:
    yamlfile:
      repo: 'https://github.com/reidmv/puppet-module-yamlfile.git'
    filemapper:
      repo: 'https://github.com/adrienthebo/puppet-filemapper.git'
      ref: '1.1.2'
    account:
      repo: 'https://github.com/jenkins-infra/puppet-account.git'
      ref: '1deebe9'
    sudo:
      repo: 'https://github.com/saz/puppet-sudo.git'
      ref: 'v3.0.6'
    irc:
      repo: 'https://github.com/jenkins-infra/puppet-irc.git'
      ref: '4e5e437'
    apachelogcompressor:
      repo: 'https://github.com/jenkins-infra/puppet-apachelogcompressor.git'

  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.15.0'
    datadog_agent:
      repo: 'datadog/datadog_agent'
      ref: '2.0.1'
    ruby:
      repo: 'puppetlabs/ruby'
      ref: '0.5.0'
    firewall:
      repo: 'puppetlabs/firewall'
      ref: '1.9.0'
    apache:
      repo: 'puppetlabs/apache'
      ref: '1.8.1'
    ntp:
      repo: 'puppetlabs/ntp'
      ref: '4.1.2'
    inifile:
      repo: 'puppetlabs/inifile'
      ref: '1.4.3'
    apt:
      repo: 'puppetlabs/apt'
      ref: '2.2.2'
    concat:
      repo: 'puppetlabs/concat'
      ref: '1.2.5'
    staging:
      repo: 'nanliu/staging'
      ref: '0.4.0'
    groovy:
      repo: 'rtyler/groovy'
      ref: '1.0.1'
    ssh:
      repo: 'saz/ssh'
      ref: '3.0.1'
    lvm:
      repo: 'puppetlabs/lvm'
      ref: '0.3.2'
    gcc:
      repo: 'puppetlabs/gcc'
      ref: '0.3.0'
    vcsrepo:
      repo: 'puppetlabs/vcsrepo'
      ref: '1.1.0'
    puppetserver_gem:
      repo: 'puppetlabs/puppetserver_gem'
      ref: '0.2.0'
    letsencrypt:
      repo: 'danzilio/letsencrypt'
      ref: '1.0.0'
    augeasproviders_shellvar:
      repo: 'herculesteam/augeasproviders_shellvar'
      ref: '2.2.1'
    augeasproviders_core:
      repo: 'herculesteam/augeasproviders_core'
      ref: '2.1.2'
    java:
      repo: 'puppetlabs/java'
      ref: '1.5.0'
    postgresql:
      repo: 'puppetlabs/postgresql'
      ref: '5.12.1'
    docker:
      repo: 'garethr/docker'
      ref: '5.3.0'
    jenkins:
      repo: 'rtyler/jenkins'
      ref: '1.7.0'
    archive:
      repo: 'puppet/archive'
      ref: '1.1.2'
    limits:
      repo: 'erwbgy/limits'
      ref: '0.3.1'
    r10k:
      repo: 'puppet/r10k'
      ref: '6.0.0'



# Setting up a couple of symlinks to make it easier to treat profiles and roles
# just as another set of "modules" in our environment
  symlinks:
    profile: "#{source_dir}/dist/profile"
    role: "#{source_dir}/dist/role"
    sshkeyman: "#{source_dir}/dist/sshkeyman"
