---
profile::openvpn::networks:
  eth0:
    # Defined in https://github.com/jenkins-infra/azure-net/blob/main/vnets.tf
    name: Subnet 'app-tier' of network 'public-vnet'
    route-metric: 100
    network_cidr: 10.244.0.0/14
  eth1:
    # Defined in https://github.com/jenkins-infra/azure/blob/main/privatek8s.tf
    name: Subnet 'privatek8s-tier' of network 'private-vnet'
    route-metric: 200
    network_cidr: 10.249.0.0/16
    peered_network_cidrs:
      # Network 'private-vnet' through peering
      - 10.248.0.0/14
profile::openvpn::vpn_network:
  name: private
  cidr: 10.248.0.0/28
  # TODO: replace by a conversion from cidr
  netmask: 255.255.255.240

profile::openvpn::auth_ldap_password: 's3cr3t'
profile::openvpn::auth_ldap_url: 'ldaps://ldap'

# Dumb Self Signed Certificate for testing purpose
profile::openvpn::openvpn_ca_pem: |
  -----BEGIN CERTIFICATE-----
  MIIDiTCCAnGgAwIBAgIUE5kg1FzG3S2HY3wmn+YKCBZddHIwDQYJKoZIhvcNAQEL
  BQAwVDELMAkGA1UEBhMCQkUxCzAJBgNVBAgMAioqMQswCQYDVQQHDAIqKjELMAkG
  A1UECgwCKioxCzAJBgNVBAMMAkNBMREwDwYJKoZIhvcNAQkBFgIqKjAeFw0xODEy
  MjIxMzAyMDhaFw0xOTEyMjIxMzAyMDhaMFQxCzAJBgNVBAYTAkJFMQswCQYDVQQI
  DAIqKjELMAkGA1UEBwwCKioxCzAJBgNVBAoMAioqMQswCQYDVQQDDAJDQTERMA8G
  CSqGSIb3DQEJARYCKiowggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDt
  ddnJMX1dzoZzzBBLeWoTqyPnPz+k+VOfi4SdxJZDBaKxuJNW7JqVq+T3PQTGtUza
  +pkXa0qD4hofCeOMAaKLj2DqcPJ8fHn7ERci6xVKd/zbSFo1C+KibFQjIVwi0MOw
  f07kxdUTWO7wUZCJICNAV6G7vHPhau2L5Of2IQWxRAtpv5GNsUTJsrS0l2Cgx0My
  4LbDefFLQnF1sIrC+A053xcgRoNGh/kyDAqCaO92zjiocHadMF88emCsAmb/KRr6
  a4i6LhV0jl1QP0xaVYRtZisM1k8Mf6+CHE225CDko3om7cMvAdkGrmPnbqKRJdij
  fI+/6Ua1IfdsaFb4/X8xAgMBAAGjUzBRMB0GA1UdDgQWBBRPHzMFkA6BJL5NEBIZ
  6QLzdBkHEDAfBgNVHSMEGDAWgBRPHzMFkA6BJL5NEBIZ6QLzdBkHEDAPBgNVHRMB
  Af8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCH0DAFkghUsLH3pP/KeiCD+Ftq
  c6chnI3m33t8zsvSNfaY26SAaLm1ercMdmz5h5ah+FLkicnhlhoZPJGf7FS0rHKW
  FI8fAEYDaSuVD05j+t0AGzPcRZKbBN1I2hdu4ly5RTxKMeQTIJr/L52C1xaeWwqh
  SMPm90//R/FGWs+aB6X9MQPFW38QaV84kPnHfrVI3+i03ClQ4B8cOxKkRV760TB0
  lHs4wEPollV1oCwdUsNolOZyr+HdGmP4Lknoycul63ZsS1NAw7ibOluBN8YtsWW2
  +ARrNnxpk0YcjRS8vZCCm+QyQcl6SqfAAqmd4zQojfNONqW14SwKwzfX4rsA
  -----END CERTIFICATE-----

# Dumb Self Signed Certificate for testing purpose
profile::openvpn::openvpn_server_pem: |
  -----BEGIN CERTIFICATE-----
  MIIDMDCCAhgCFGXhX2+qymGO4kQ1BmlX+ALRP8g7MA0GCSqGSIb3DQEBCwUAMFQx
  CzAJBgNVBAYTAkJFMQswCQYDVQQIDAIqKjELMAkGA1UEBwwCKioxCzAJBgNVBAoM
  AioqMQswCQYDVQQDDAJDQTERMA8GCSqGSIb3DQEJARYCKiowHhcNMTgxMjIyMTMw
  MjA4WhcNMTkwMTIxMTMwMjA4WjBVMQswCQYDVQQGEwJCRTELMAkGA1UECAwCKiox
  CzAJBgNVBAcMAioqMQswCQYDVQQKDAIqKjEMMAoGA1UEAwwDdnBuMREwDwYJKoZI
  hvcNAQkBFgIqKjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAM43fnRx
  Mb8hcDBbqjZ4FIBzPxJLOHQ7XR3mFMLjiNSxgFT7zAFbV6NPj5k3u60Y4XEnAcOO
  4Oog4tTkpK93+JBBGWS/6EqZTzVPu26UEoi16JfLZ7rAuVcdPUOVq2XzeQUGRQII
  aB8nCrLMzHVWEGDMzDu8Fq9T7fNpAktir9omJI6a5moGFVSDLTJpskKFWvXYYF2+
  GXN7BsKqN4k2zQbldTdKq0xplbkgzbn/eIM0e7YTP09lnnkQSzXqaoM1t+XSGawC
  YxVOIUb3GETZJYZ+KFwyzgkpyNvM2VHNE7MaklggqmfM57HL+b3gc8Zzd+DPErRL
  ZY0MDysKwVRMOW0CAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAGNUSGbuQvnF8E7hr
  smCYDp+DhsDhko9odCL/KAHWQw3PR0qEvVe5tIykLDv/lc/3AkATXhhNmDrXduwc
  Mgs4K/db7Hsk8IFmOhKqBw8/CHrGJ+n/u7f45xTxpu5XeXsUGHNJOxa+dYu20186
  I6VQSN14YpQ75zQ4tFoWJlOMeJmomQ78YbBRszftAGQZGaR9P+6pbmkpLDo1gudG
  DiUt7X2fGqZ+w7cQxyuNLIeMITGIkQn+J/Ow5NBcXeL1AzMetBgoy4t94J6F0dHM
  HfvrHHBQRxwmTaDOc+0pnqFcRu+GCelUMtlpTTfCCR5qYIeGgPB2LtPqpW/XHRMP
  4ZlfnQ==
  -----END CERTIFICATE-----

# Dumb Private Key for testing purpose
profile::openvpn::openvpn_server_key: |
  -----BEGIN PRIVATE KEY-----
  MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDON350cTG/IXAw
  W6o2eBSAcz8SSzh0O10d5hTC44jUsYBU+8wBW1ejT4+ZN7utGOFxJwHDjuDqIOLU
  5KSvd/iQQRlkv+hKmU81T7tulBKIteiXy2e6wLlXHT1Dlatl83kFBkUCCGgfJwqy
  zMx1VhBgzMw7vBavU+3zaQJLYq/aJiSOmuZqBhVUgy0yabJChVr12GBdvhlzewbC
  qjeJNs0G5XU3SqtMaZW5IM25/3iDNHu2Ez9PZZ55EEs16mqDNbfl0hmsAmMVTiFG
  9xhE2SWGfihcMs4JKcjbzNlRzROzGpJYIKpnzOexy/m94HPGc3fgzxK0S2WNDA8r
  CsFUTDltAgMBAAECggEAKGFDeMelhxikIEQCy5Gt6g0nH4ztLA1nyXABRrxJUeTE
  DWAU7XsWaRsuMkFwlY+WrZKGzOVQc2gnIqr2+IkUeiLVNx5A/UKR+Q141UlXa7+7
  IOYqlK4iXMWT9oT7QAZx/yLgJmrBAMCjXqmtq5hDssDHiTbmdkSIBq7cTSiw6JVP
  M+nkmv9Qrv3Y/lQLJF7KKCWVOcWm7uQwN8jiLPLzeRSS8xLSlgKedmWkIjskpLkE
  3vvr8NoLAUTLq/dnO5Igj0cMKS2mGKlN46aDlkd7EopY13kABLHKfSSWst9bGfYD
  7kBQaXA1S9Nj67tMhUZfSwB6JrXb2wK/IeWuH5N04QKBgQD45N5B1dpZzEIYIhez
  r+R0Dosu/OpG6zsBQmLbg2WMN4LGfbgFD+oPL8myY6IBEF/IpStTuG8RXeP8v1x8
  J0NKkkc3SDjYLPIjcoLShAf8TlRQoGZCNdi1r3D0wSb8XVgMElboMSlzHTqzJTpG
  OdPCuvmWez56QOWQ6xJ91MqYmQKBgQDUGrQnhf0tz71DLmwElsd41B2/bMdwsY+n
  bJZlgGs1MwwvVyGWcL1G4VntzB2xip3E64GqV6qmVbnh97Mw6Ho7/EZ97J5J45qE
  8UWWjIzo8dYcZnE2O3O4zr0gFRYVO+yUCCRkR9JhNaiPkNMtR04Bw0XK6o1588lA
  LVJUv5wH9QKBgQC3HtyPn6HpE6lFTEAYCj+RS+oHhjlwOD3PbWKCkygxg94J4BF2
  WAEjb0t8nmVhVwTCARPhov7EzkmhecG37sNJqFoRSGfaVSdKAURTUqT1c0QBliHm
  cOuisRPwX/QpFRxktVGPwCv47/ZyO9+mL4Gn8h0UJFURaZH9j5apUdhFcQKBgEei
  dTHcCPQN80fbR9QM8HWYfiuGm50t+ux6uhix1IN1KCpc7RUYInTr6ylrBKRPwpUd
  TP+w+AuRbGQq+jQMcCwOOeiRn6wo2KkJq4z7DyQleUDCQH4meiDygeFx/bFSOcaN
  MW1E7IK0UqeaLBhgurHRt6KesQV9Fn08UVAaHqJ5AoGBALEqZxgPJnUMwbPKDzRt
  YYd1C0nfZ3edeoSaJuCLU1qUWcuqxhFbGRIhT9MvXhStDKljDH3efXdpVyhIT+RI
  yEkzrvH9HyTiaK2dzJuq0rItU2rHYz/sckafpwtwRjxEffIcBcJh0L5JlU6yYBzP
  fbID8N632RFEBJgAg02JhYW0
  -----END PRIVATE KEY-----

# Dumb dh certificate for testing purpose
profile::openvpn::openvpn_dh_pem: |
  -----BEGIN DH PARAMETERS-----
  MIIBCAKCAQEA85Md0iWYllvKYyO5Xe2yNLgzEyWhUw56ol5kVbrQVchT4yAU4Jkp
  pXcrXnyhn/J1wlhFg3zUdesYNoeNYH9LeRUTFddh8h6Qbwb6DbK6MZu89uSL2hHn
  7wLZOjpkRoIxHzN6nMBj6cpryVi15GJgXT4CDzBvHtDYFd+m9XA2OJoMauZBOB2F
  uUVGZRHott7G+f4ooi3iXkHArJEllyavDFL2wuTgsD9IMEN+UBt4MAiJbDiNnNYT
  M/5EwDFZREQ3tx2xol8uTbnfuIm/OQKW1OqmFKvNCwF8I7SdK9pIHHAyPBNe37vw
  KylZSP3kLe6g3qpUb82MTsYNIDUz5XQ7UwIBAg==
  -----END DH PARAMETERS-----
