github:
  user: "Jenkins Infra Bot (updatecli)"
  email: "60776566+jenkins-infra-bot@users.noreply.github.com"
  token: "UPDATECLI_GITHUB_TOKEN"
  branch: "main"
  owner: "jenkins-infra"
  repository: "jenkins-infra"
