github:
  user: "Jenkins Infra Bot (updatecli)"
  email: "60776566+jenkins-infra-bot@users.noreply.github.com"
  username: "jenkins-infra-bot"
  token: "UPDATECLI_GITHUB_TOKEN"
  branch: "production"
  owner: "jenkins-infra"
  repository: "jenkins-infra"

jdks:
  - major: 21
  - major: 25

windowsVersions:
  - version: 2019
  - version: 2022
  - version: 2025

nodejs_consumers:
  - repository: plugin-site
  - repository: contributor-spotlight
  - repository: stats.jenkins.io
  - repository: docs.jenkins.io
  - repository: stories
  - repository: jenkins-io-components
  - repository: gatsby-plugin-jenkins-layout
  - repository: incrementals-publisher
